name: Build and Publish New Release

on:
  push:
    tags:
      - "v*" # Запускается при создании тега версии (например, v1.0.0)
  workflow_dispatch: # Возможность запуска вручную

permissions:
  contents: write # Разрешение на создание релизов и загрузку файлов

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    permissions:
      contents: write
      id-token: none
      attestations: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TwoClean-exe
          path: target/release/TwoClean.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            # Новая версия ${{ github.ref_name }}

            ## Установка
            Скачайте файл `TwoClean.exe` и запустите его.

            ## Системные требования
            - Windows 10/11
          files: target/release/TwoClean.exe
          draft: false
          prerelease: false
